### PR TITLE
Fix autobinding

### PR DESCRIPTION
**Pull request by CaryWill**
Change some methods in React component to arrow function to enable autobinding.

### CODE REVIEW

**Comment by leitdeux** [comment]
Thanks for checking out my code and submitting this pull request, @CaryWill. Is there a strong benefit here to changing those methods to arrow functions? Curious why you prefer to arrow functions in this case. Thanks!

**Comment by CaryWill** [comment]
Oh, I thought it's just a syntax error, since in React components declared as ES6 classes, methods follow the same semantics as regular ES6 classes. This means that they don’t automatically bind this to the instance. You’ll have to explicitly use .bind(this) in the constructor, so that's why I changed methods to arrow function.
Is there anything I missed?

**Comment by leitdeux** [comment]
I don't believe that autobinding is necessary for those particular class methods because aren't they already bound to the class instance? The `getTextOrientation` method, for example, doesn't need to bind `this` explicitly or use arrow function autobinding for it to be correctly invoked within the component `render()` method:
```js

class Hanko extends Component {
  
  getTextOrientation() {
    // ...
  }

  render() {
    // executes getTextOrientation as expected, with or without an arrow function used in the method declaration
    const textOrientation = this.getTextOrientation();
  
    // with explicit binding:
    // const textOrientation = this.getTextOrientation.bind(this)();
  }
}
```

**Comment by CaryWill** [comment]
Oh, yes! Thanks for the explanation.

**Comment by leitdeux** [comment]
No problem, thanks for looking through the code! :)

**Pull request closed without merging**
